---
title: "Untitled"
author: "Ismail Guennouni"
date: "2023-05-16"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(depmixS4)

knitr::opts_chunk$set(echo = TRUE)
```


```{r}
origin_dat <- read.csv("data/longFormData.csv") 

origin_dat <- origin_dat %>% mutate(investment_bin = cut(investment, breaks = c(-1,2.5,7.5,12.5,17.5,21)),
                                    return_pct_bin = cut(return_pct, breaks = c(-.1,.125,.325,.51,.755,1.1)),
                                    next_investment = lead(investment, default=0),
                                            invPnL = return - investment,
                                            trPnL = 3*investment - return)
```



# Support functions and discrete Gaussian class construction 
```{r supportHMM, include=FALSE}
# # order the states of the HMM to allow it to order them as low ret/mid/ret/high ret. 
# label_switch <- function(mod,labels) {
#   # labels is vector, first element is new label for original state 1, second is new label for original state 2, etc.
#   if(!is(mod,"depmix") || !is(mod,"depmix.fitted")) stop("this function is for depmix models")
#   n_states <- mod@nstates
#   if(length(labels) != n_states || length(unique(labels)) != n_states || !(all(labels) %in% 1:n_states)) {
#     stop("labels needs to be a vector of unique integers between 1 and", n_states)
#   }
#   inv_labels <- sapply(1:n_states,function(x) which(labels == x))
#   tmp <- mod
#   # relabel prior
#   ppars <- getpars(mod@prior)
#   fpars <- getpars(mod@prior,which="fixed")
#   out_pars <- as.numeric(t(matrix(ppars,nrow=length(ppars)/n_states,byrow = TRUE)[,inv_labels]))
#   out_fixed <- as.logical(t(matrix(fpars,nrow=length(fpars)/n_states,byrow = TRUE)[,inv_labels]))
#   if(!tmp@prior@family$link=="identity") tmp@prior@family$base <- labels[tmp@prior@family$base]
#   # relabel transition
#   for(i in 1:n_states) {
#     ppars <- getpars(mod@transition[[inv_labels[i]]])
#     fpars <- getpars(mod@transition[[inv_labels[i]]], which="fixed")
#     out_pars <- c(out_pars,as.numeric(t(matrix(ppars,nrow=length(ppars)/n_states,byrow = TRUE)[,inv_labels])))
#     out_fixed <- c(out_fixed,as.logical(t(matrix(fpars,nrow=length(fpars)/n_states,byrow = TRUE)[,inv_labels])))
#     tmp@transition[[i]] <- mod@transition[[inv_labels[i]]]
#     if(!tmp@transition[[i]]@family$link=="identity") tmp@transition[[i]]@family$base <- labels[tmp@transition[[i]]@family$base]
#     #out_pars <- c(out_pars,getpars(mod@transition[[inv_labels[i]]]))
#   }
#   # relabel response
#   for(i in 1:n_states) {
#     out_pars <- c(out_pars,unlist(lapply(mod@response[[inv_labels[i]]],getpars)))
#     out_fixed <- c(out_fixed,unlist(lapply(mod@response[[inv_labels[i]]],getpars,which="fixed")))
#   }
#   tmp <- setpars(tmp,out_fixed,which="fixed")
#   tmp <- setpars(tmp,out_pars)
#   if(is(tmp,"depmix.fitted")) tmp@posterior <- viterbi(tmp)
#   return(tmp)
# }
# 
# # ORDERING STATES WHEN RESPONSE IS BINS
# order_mod <- function(mod) {
#   ns <- nstates(mod)
#   sum <- rep(0.0,ns)
#   for(i in 1:ns) {
#     # Expected return in each state calculation (5 bins, for binned returns)
#     sum[i] = sum(1:5*mod@response[[i]][[1]]@parameters$coefficients)
#   }
#   # reordering the states
#   mod <- label_switch(mod, rank(sum))
#   return(mod)
# }
# 
# # ORDERING STATES WHEN RESPONSE IS GAUSSIAN
# order_mod_gauss <- function(mod) {
#   ns <- nstates(mod)
#   sum <- rep(0.0,ns)
#   for(i in 1:ns) {
#     # Expected return in each state calculation 
#     sum[i] = mod@response[[i]][[1]]@parameters$mu
#   }
#   # reordering the states
#   mod <- label_switch(mod, rank(sum))
#   return(mod)
# }

```

```{r, include=F}
# define a response class which only contains the standard slots, no additional slots
setClass("discgaus", contains="response", slots=c(breaks="numeric"))

# define a generic for the method defining the response class

setGeneric("discgaus", function(y, pstart = NULL, fixed = NULL, ...) standardGeneric("discgaus"))

# define the method that creates the response class

setMethod("discgaus", 
          signature(y="ANY"), 
          function(y,pstart=NULL,fixed=NULL, breaks = c(-Inf, seq(0, 19) + .5, Inf), ...) {
            y <- matrix(y,length(y))
            x <- matrix(1)
            parameters <- list()
            npar <- 2
            if(is.null(fixed)) fixed <- as.logical(rep(0,npar))
            if(!is.null(pstart)) {
              if(length(pstart)!=npar) stop("length of 'pstart' must be ",npar)
              parameters$mu <- pstart[1]
              parameters$sigma <- pstart[2]
            } else {
              parameters <- list(mu = 10, sigma = 3)
            }
            mod <- new("discgaus",parameters=parameters,fixed=fixed,x=x,y=y,npar=npar, breaks=breaks)
            mod
          }
)

setMethod("show","discgaus",
          function(object) {
            cat("Gaussian with discrete support\n")
            cat("Parameters: \n")
            cat("mu: ", object@parameters$mu, "\n")
            cat("sigma: ", object@parameters$sigma, "\n")
          }
)

setMethod("dens","discgaus",
          function(object,log=FALSE) {
            p <- pnorm(object@breaks[-1], mean = object@parameters$mu, sd = object@parameters$sigma) - pnorm(object@breaks[-length(object@breaks)], mean = object@parameters$mu, sd = object@parameters$sigma)
            if(log) return(log(p[as.numeric(cut(object@y, breaks=object@breaks))])) else return(p[as.numeric(cut(object@y, breaks=object@breaks))])
          }
)

setMethod("setpars","discgaus",
          function(object, values, which="pars", ...) {
            npar <- npar(object)
            if(length(values)!=npar) stop("length of 'values' must be",npar)
            # determine whether parameters or fixed constraints are being set
            nms <- names(object@parameters)
            switch(which,
                   "pars"= {
                     object@parameters$mu <- values[1]
                     object@parameters$sigma <- values[2]
                   },
                   "fixed" = {
                     object@fixed <- as.logical(values)
                   }
            )
            names(object@parameters) <- nms
            return(object)
          }
)

setMethod("getpars","discgaus",
          function(object,which="pars",...) {
            switch(which,
                   "pars" = {
                     parameters <- numeric()
                     parameters <- unlist(object@parameters)
                     pars <- parameters
                   },
                   "fixed" = {
                     pars <- object@fixed
                   }
            )
            return(pars)
          }
)

setMethod("fit","discgaus",
          function(object,w) {
            if(missing(w)) w <- NULL
            if(!is.null(w)) {
              negLL <- function(pars) {
                object <- setpars(object, c(pars[1], exp(pars[2])))
                -sum(w*log(dens(object)))
              }
            } else {
              negLL <- function(pars) {
                object <- setpars(object, c(pars[1], exp(pars[2])))
                -sum(log(dens(object)))
              }
            }
            pars <- optim(c(object@parameters$mu, log(object@parameters$sigma)), fn=negLL)$par
            object <- setpars(object,c(pars[1], exp(pars[2])))
            object
          }
)

setClass("truncdiscgaus", contains="discgaus", slots=c(min="numeric", max="numeric"))

setMethod("dens","truncdiscgaus",
          function(object,log=FALSE) {
            breaks <- c(object@min, object@breaks[object@breaks > object@min & object@breaks < object@max], object@max)
            prec <- pnorm(object@max, mean = object@parameters$mu, sd = object@parameters$sigma) - pnorm(object@min, mean = object@parameters$mu, sd = object@parameters$sigma)
            if(prec < 1e-12) {
              # return uniform probabilities as precision is likely off
              p <- rep(1/(length(breaks)-1), length(object@y))
              if(log) return(log(p)) else return(p)
            } else {
              p <- pnorm(breaks[-1], mean = object@parameters$mu, sd = object@parameters$sigma) - pnorm(breaks[-length(breaks)], mean = object@parameters$mu, sd = object@parameters$sigma)
              p <- p/sum(p)
              if(log) return(log(p[as.numeric(cut(object@y, breaks=object@breaks))])) else return(p[as.numeric(cut(object@y, breaks=object@breaks))])
            }
          }
)

setGeneric("truncdiscgaus", function(y, pstart = NULL, fixed = NULL, ...) standardGeneric("truncdiscgaus"))

setMethod("truncdiscgaus", 
          signature(y="ANY"), 
          function(y,pstart=NULL,fixed=NULL, breaks = c(-Inf, seq(0, 19) + .5, Inf), min=-0.5, max=20.5, ...) {
            y <- matrix(y,length(y))
            x <- matrix(1)
            parameters <- list()
            npar <- 2
            if(is.null(fixed)) fixed <- as.logical(rep(0,npar))
            if(!is.null(pstart)) {
              if(length(pstart)!=npar) stop("length of 'pstart' must be ",npar)
              parameters$mu <- pstart[1]
              parameters$sigma <- pstart[2]
            }
            mod <- new("truncdiscgaus",parameters=parameters,fixed=fixed,x=x,y=y,npar=npar, breaks=breaks, min=min, max=max)
            mod
          }
)

# define a response class which only contains the standard slots, no additional slots
setClass("vtdgaus", contains="response", slots=c(yield="numeric"))

# define a generic for the method defining the response class

setGeneric("vtdgaus", function(y, pstart = NULL, fixed = NULL, ...) standardGeneric("vtdgaus"))

# define the method that creates the response class

setMethod("vtdgaus", 
          signature(y="ANY"), 
          function(y, yield, pstart=NULL,fixed=NULL, ...) {
            y <- matrix(y,length(y))
            x <- matrix(1)
            parameters <- list()
            npar <- 2
            if(is.null(fixed)) fixed <- as.logical(rep(0,npar))
            if(!is.null(pstart)) {
              if(length(pstart)!=npar) stop("length of 'pstart' must be ",npar)
              parameters$mu <- pstart[1]
              parameters$sigma <- pstart[2]
            } else {
              parameters <- list(mu=.5,sigma=1)
            }
            mod <- new("vtdgaus",parameters=parameters,fixed=fixed,x=x,y=y,npar=npar, yield=yield)
            mod
          }
)

setMethod("show","vtdgaus",
  function(object) {
    cat("Gaussian with variable discrete support for percentage responses\n")
    cat("Parameters: \n")
    cat("mu: ", object@parameters$mu, "\n")
    cat("sigma: ", object@parameters$sigma, "\n")
  }
)

setMethod("dens","vtdgaus",
  function(object,log=FALSE) {
      # determine cuts for pnorm based on 
      #p <- pnorm(sapply(object@y + .5*(1/object@yield), function(x) min(x,1.001)), mean = object@parameters$mu, sd = object@parameters$sigma) - pnorm(sapply(object@y - .5*(1/object@yield),function(x) max(x,-0.001)), mean = object@parameters$mu, sd = object@parameters$sigma)
      #norm <- (pnorm(1 + .001, mean = object@parameters$mu, sd = object@parameters$sigma) - pnorm(-0.001, mean = object@parameters$mu, sd = object@parameters$sigma))
      #p <- p/norm
    
      # alternatively, normalize factor based on size of cuts
    
      prec <- pnorm(1 + .5*(1/60), mean = object@parameters$mu, sd = object@parameters$sigma) - pnorm(0 - .5*(1/60), mean = object@parameters$mu, sd = object@parameters$sigma)
      # check for issues with precision, using highest yield
      if(prec < 1e-12) {
        p <- 1/(object@yield + 1)
      } else {
        p <- pnorm(object@y + .5*(1/object@yield), mean = object@parameters$mu, sd = object@parameters$sigma) - pnorm(object@y - .5*(1/object@yield), mean = object@parameters$mu, sd = object@parameters$sigma)
        norm <- pnorm(1 + .5*(1/object@yield), mean = object@parameters$mu, sd = object@parameters$sigma) - pnorm(0 - .5*(1/object@yield), mean = object@parameters$mu, sd = object@parameters$sigma)
        p <- p/norm
      }
      # probability when yield == 0 is always 1 
      p[object@yield == 0] <- 1
      if(log) return(log(p)) else return(p)
    }
)

setMethod("setpars","vtdgaus",
          function(object, values, which="pars", ...) {
            npar <- npar(object)
            if(length(values)!=npar) stop("length of 'values' must be",npar)
            # determine whether parameters or fixed constraints are being set
            nms <- names(object@parameters)
            switch(which,
                   "pars"= {
                     object@parameters$mu <- values[1]
                     object@parameters$sigma <- values[2]
                   },
                   "fixed" = {
                     object@fixed <- as.logical(values)
                   }
            )
            names(object@parameters) <- nms
            return(object)
          }
)

setMethod("getpars","vtdgaus",
          function(object,which="pars",...) {
            switch(which,
                   "pars" = {
                     parameters <- numeric()
                     parameters <- unlist(object@parameters)
                     pars <- parameters
                   },
                   "fixed" = {
                     pars <- object@fixed
                   }
            )
            return(pars)
          }
)

setMethod("fit","vtdgaus",
          function(object,w) {
            if(missing(w)) w <- NULL
            if(!is.null(w)) {
              negLL <- function(pars) {
                object <- setpars(object, c(pars[1], exp(pars[2])))
                -sum(w*log(dens(object)))
              }
            } else {
              negLL <- function(pars) {
                object <- setpars(object, c(pars[1], exp(pars[2])))
                -sum(log(dens(object)))
              }
            }
            pars <- optim(c(object@parameters$mu, log(object@parameters$sigma)), fn=negLL)$par
            object <- setpars(object,c(pars[1], exp(pars[2])))
            object
          }
)
```



```{r}
#| label: HMM-support-functions
#| include: false
# order the states of the HMM to allow it to order them as low ret/mid/ret/high ret. 
label_switch <- function(mod,labels) {
  # labels is vector, first element is new label for original state 1, second is new label for original state 2, etc.
  if(!is(mod,"depmix") || !is(mod,"depmix.fitted")) stop("this function is for depmix models")
  n_states <- mod@nstates
  if(length(labels) != n_states || length(unique(labels)) != n_states || !(all(labels) %in% 1:n_states)) {
    stop("labels needs to be a vector of unique integers between 1 and", n_states)
  }
  inv_labels <- sapply(1:n_states, function(x) which(labels == x))
  tmp <- mod
  # relabel prior
  ppars <- getpars(mod@prior)
  fpars <- getpars(mod@prior, which="fixed")
  out_pars <- as.numeric(t(matrix(ppars,nrow=length(ppars)/n_states,byrow = TRUE)[,inv_labels]))
  out_fixed <- as.logical(t(matrix(fpars,nrow=length(fpars)/n_states,byrow = TRUE)[,inv_labels]))
  if(!tmp@prior@family$link=="identity") tmp@prior@family$base <- labels[tmp@prior@family$base]
  # relabel transition
  for(i in 1:n_states) {
    ppars <- getpars(mod@transition[[inv_labels[i]]])
    fpars <- getpars(mod@transition[[inv_labels[i]]], which="fixed")
    out_pars <- c(out_pars,as.numeric(t(matrix(ppars,nrow=length(ppars)/n_states,byrow = TRUE)[,inv_labels])))
    out_fixed <- c(out_fixed,as.logical(t(matrix(fpars,nrow=length(fpars)/n_states,byrow = TRUE)[,inv_labels])))
    tmp@transition[[i]] <- mod@transition[[inv_labels[i]]]
    if(!tmp@transition[[i]]@family$link=="identity") tmp@transition[[i]]@family$base <- labels[tmp@transition[[i]]@family$base]
    #out_pars <- c(out_pars,getpars(mod@transition[[inv_labels[i]]]))
  }
  # relabel response
  for(i in 1:n_states) {
    out_pars <- c(out_pars,unlist(lapply(mod@response[[inv_labels[i]]],getpars)))
    out_fixed <- c(out_fixed,unlist(lapply(mod@response[[inv_labels[i]]],getpars,which="fixed")))
  }
  tmp <- setpars(tmp,out_fixed,which="fixed")
  tmp <- setpars(tmp,out_pars)
  if(is(tmp,"depmix.fitted")) tmp@posterior <- viterbi(tmp)
  return(tmp)
}

# ordering states for a truncated discretised Gaussian
order_mod_truncdiscgaus <- function(mod) {
  ns <- nstates(mod)
  sum <- rep(0.0,ns)
  for(i in 1:ns) {
    # Expected return in each state calculation
    tpars <- getpars(mod@response[[i]][[1]])
    dmod <- truncdiscgaus(seq(0, 20), pstart = tpars, min=-0.5, max=20.5)
    sum[i] <- sum(seq(0,20)*dens(dmod))
  }
  cat("Expected values for states: ",sum, "\n")
  # reordering the states
  mod <- label_switch(mod, rank(sum, ties.method = "first"))
  return(mod)
}

# ordering states for a variable response truncated discretised Gaussian
order_mod_vtdgaus <- function(mod) {
  ns <- nstates(mod)
  sum <- rep(0.0,ns)
  for(i in 1:ns) {
    # Expected return in each state calculation
    tpars <- getpars(mod@response[[i]][[1]])
    dmod <- vtdgaus(seq(0, 1, length=61), pstart = tpars, yield=rep(60, 61))
    sum[i] <- sum(seq(0, 1, length=61)*dens(dmod))
  }
  # reordering the states
  mod <- label_switch(mod, rank(sum, ties.method = "first"))
  return(mod)
}
```


```{r}
#| label: fit-HMM-investor-models
#| include: false
#| cache: true

inv_fdmod <- list()

set.seed(20230824)

for(i in 2:4) {
  inv_simple <- depmix(investment_bin ~ 1, data = origin_dat, nstates = i, transition = ~ invPnL, family=multinomial("mlogit"), ntimes = rep(10,381))
  
  mus <- (1:i)*(20/(i+1))
  sigmas <- rep((20/(i+1)), i)
  rModels_inv <- list()
  for(s in 1:i) {
    rModels_inv[[s]] <- list(truncdiscgaus(origin_dat$investment, pstart=c(mus[s],sigmas[s]), min=-0.5, max=20.5))
  }
  
  #rModels_inv <- rep(list(list(truncdiscgaus(origin_dat$investment, pstart=c(10,5), min=-0.5, max=20.5))), each=i)
  
  inv_dmod <- makeDepmix(response=rModels_inv, transition=inv_simple@transition, prior=inv_simple@prior, ntimes = rep(10,381), homogeneous=FALSE)
  
  inv_fdmod[[i]] <- fit(inv_dmod, emcontrol = em.control(random.start = FALSE))
  
  #inv_fdmod[[i]] <- multistart(inv_dmod, nstart=20)
}

#ORDER THE STATES OF THE HMM
mod_3S  <- order_mod_truncdiscgaus(inv_fdmod[[3]])

```




```{r}
# # Specify simple models to copy transition and prior
# inv_simple <- list()
# for(i in 2:6) {
#   inv_simple[[i]] <- depmix(investment_bin ~ 1, data = origin_dat, nstates = i, transition = ~ invPnL, family=multinomial("mlogit"), ntimes = rep(10,381))
# }
# 
# 
# # Specify truncated gaussian models for 3 state model 
# rModels3 <- list(
#   list(
#     truncdiscgaus(origin_dat$investment,pstart=c(5,2), min=-.5, max=20.5) # first guassian initialised with mean of 5 and sd of 2
#   ),
#   list(
#     truncdiscgaus(origin_dat$investment,pstart=c(10,2), min=-.5, max=20.5)
#   ),
#   list(
#     truncdiscgaus(origin_dat$investment,pstart=c(15,2), min=-.5, max=20.5)
#   )
# )
# 
# inv_dmod_3 <- makeDepmix(response=rModels3,transition=inv_simple[[3]]@transition,prior=inv_simple[[3]]@prior,ntimes = rep(10,381), homogeneous=FALSE)
# 
# inv_fdmod_3 <- fit(inv_dmod_3, emcontrol=em.control(random.start = FALSE))  #random.start = FALSE -> use parameters supplied as starting values
# 
# mod_3S <- order_mod_gauss(inv_fdmod_3)

```


```{r, include=F}

# 
# state1 <- dens(truncdiscgaus(seq(0:20) - 1,pstart=c(unlist(mod_3S@response[[1]][[1]]@parameters)), breaks = c(-Inf, 0:19 + .5, Inf), min=0, max=20))
# 
# state2 <- dens(truncdiscgaus(seq(0:20) - 1,pstart=c(unlist(mod_3S@response[[2]][[1]]@parameters)), breaks = c(-Inf, 0:19 + .5, Inf), min=0, max=20))
# 
# state3 <- dens(truncdiscgaus(seq(0:20) - 1,pstart=c(unlist(mod_3S@response[[3]][[1]]@parameters)), breaks = c(-Inf, 0:19 + .5, Inf), min=0, max=20))
# 
# investment <- seq(0:20) - 1
# 
# inv_resp_3S <- as.data.frame(cbind(investment,state1,state2,state3)) %>% 
#   pivot_longer(cols=c("state1","state2","state3"),
#                     names_to='investor_state',
#                     values_to='probability') 

#####################
inv_policy <- list()
for(i in 1:3) {
  inv_policy[[i]] <- dens(truncdiscgaus(seq(0,20),  pstart=c(unlist(mod_3S@response[[i]][[1]]@parameters)), breaks = c(-Inf, seq(0, 19) + .5, Inf), min=-0.5, max=20.5))
}

investment <- seq(0,20)

df_inv_policy <- data.frame(investor_state = rep(1:3, each=length(investment)),
                            investment,
                            probability = unlist(inv_policy))

#####################

```

```{r}
#| label: fig-policy-plot-3-state-HMM
#| echo: false
#| fig.cap: Probability mass function of the investor's policy conditional on its latent state as an output of the best fitting 3 state HMM using a truncated discretised Gaussian as a response function
#| fig.align: center
#| fig.width: 8
#| fig.height: 4

plotinvHMM <- ggplot(df_inv_policy ,                            
       aes(x = investment,
           y = probability,
           fill = factor(paste0("s",investor_state)))) +
  geom_bar(stat = "identity",
           position = "dodge") + 
  labs(fill='Latent investor state') +
  theme_minimal() + 
  theme(legend.position = "bottom")

plotinvHMM

```

```{r}
# inv_resp_3S %>% mutate( investor_state = fct_recode(investor_state, "low-trust" = "state1", "medium-trust" = "state2", "high-trust" = "state3"))%>%
#         ggplot( aes(x = investment,
#                     y = probability,
#                     fill = investor_state)) +
#   geom_bar(stat = "identity",
#            position = "dodge") + 
#   labs(fill='Latent investor state') +
#   theme_bw() + 
#   theme(legend.position = "bottom")

```


Let's write a function to plot transition functions given parameters 


```{r}
#| label: transition-plot-function
#| include: false
#| warning: false
plot_transitions_PnL <- function(fmod) {

  ns <- nstates(fmod)
  
  trans_prob <- data.frame(
    from = rep(1:ns, each=80*ns),
    to = rep(1:ns, each=80),
    PnL = seq(-20,60,length=80),
    prob = 0
  )

  y <- matrix(0.0,ncol=ns, nrow=80)
  
  for(from in 1:ns) {
    pars <- matrix(getpars(fmod)[seq(ns + 1 + (from - 1)*2*ns, ns + 1 + (from - 1)*2*ns + 2*ns - 1)],ncol=2)
    for(to in 1:ns) {
      x <- trans_prob[trans_prob$from == from & trans_prob$to == to,"PnL"]
      y[,to] <- exp(pars[to,1] + pars[to,2]*x)
    }
    y <- y/rowSums(y)
    for(to in 1:ns) {
      trans_prob$prob[trans_prob$from == from & trans_prob$to == to] <- y[,to]
    }
  }
  
  trans_prob <- trans_prob %>%
    mutate(from = paste0("s", from),
           to = paste0("s", to))
  
  # trans_prob <- trans_prob %>% mutate(from=recode(from, 
  #                        `1`="low-trust",
  #                        `2`="medium-trust",
  #                        `3`="high-trust"),
  #                       to=recode(to, 
  #                        `1`="low-trust",
  #                        `2`="medium-trust",
  #                        `3`="high-trust")) %>% 
  #   mutate(across(from, factor, levels=c("low-trust","medium-trust","high-trust"))) %>% 
  #   mutate(across(to, factor, levels=c("low-trust","medium-trust","high-trust")))
  ggplot(trans_prob,aes(x=PnL,y=prob, colour = as.factor(to))) + geom_line() + facet_wrap(~from) + ylim(c(0,1))
}
```

```{r}
#| label: transition-plot-investor-HMM-3-state
#| echo: false
#| fig.cap: Transition probabilities of the investor state as a function of investor gain in the current round. Each panel is the state transitioned from, and each line shows the probability of transitioning to the state identified by the line color.
#| fig.align: center
#| fig.width: 8
#| fig.height: 4
plot_transitions_PnL(mod_3S) + labs(x = "Investor gain", y = "Probability", color='Transition to') + theme_bw() + theme(legend.position = "bottom") 
```


## Write function to plot transition probs based on input of trans matrix

```{r}
# plot_transitions_input <- function(pars_list) {
# 
#   ns <- nrow(pars_list[[1]])  # number of states
#   
#   trans_prob <- data.frame(
#     from = rep(1:ns, each=80*ns),
#     to = rep(1:ns, each=80),
#     PnL = seq(-20,60,length=80),
#     prob = 0
#   )
# 
#   y <- matrix(0.0,ncol=ns, nrow=80)
#   
#   for(from in 1:ns) {
#     pars <- pars_list[[from]]
#     for(to in 1:ns) {
#       x <- trans_prob[trans_prob$from == from & trans_prob$to == to,"PnL"]
#       y[,to] <- exp(pars[to,1] + pars[to,2]*x)
#     }
#     y <- y/rowSums(y)
#     for(to in 1:ns) {
#       trans_prob$prob[trans_prob$from == from & trans_prob$to == to] <- y[,to]
#     }
#   }
#   
#   trans_prob <- trans_prob %>% mutate(from=recode(from, 
#                          `1`="low-trust",
#                          `2`="medium-trust",
#                          `3`="high-trust"),
#                         to=recode(to, 
#                          `1`="low-trust",
#                          `2`="medium-trust",
#                          `3`="high-trust")) %>% 
#     mutate(across(from, factor, levels=c("low-trust","medium-trust","high-trust"))) %>% 
#     mutate(across(to, factor, levels=c("low-trust","medium-trust","high-trust")))
#    
#   ggplot(trans_prob,aes(x=PnL,y=prob, colour = as.factor(to))) + geom_line() + facet_wrap(~from) + ylim(c(0,1))+
#       theme(legend.position = "bottom")
# }
# 


```


```{r}
plot_HMM_transitions <- function(ns, pars_mat) {

  trans_prob <- data.frame(
    from = rep(1:ns, each=100*ns),
    to = rep(1:ns, each=100),
    ret = seq(-20,60,length=100),
    probs = 0
  )
  
  
  y <- matrix(0.0,ncol=ns, nrow=100)
  
  for(from in 1:ns) {
  pars <- matrix(pars_mat[[from]], ncol=2)
  # print(pars)
  
    for(to in 1:ns) {
        x <- trans_prob[trans_prob$from == from & trans_prob$to == to,"ret"]
        y[,to] <- exp(pars[to,1] + pars[to,2]*x)
    }
    y <- y/rowSums(y)

    
    for(to in 1:ns) {
      trans_prob$probs[trans_prob$from == from & trans_prob$to == to] <- y[,to]
    }
  }
  
  df <- as.data.frame(trans_prob) %>% 
    mutate(from = recode(from, "1" = "low-trust", "2" = "medium-trust", "3" = "high-trust"),
           to = recode(to, "1" = "low-trust", "2" = "medium-trust", "3" = "high-trust") ) %>% 
    mutate(across(from, factor, levels=c("low-trust","medium-trust","high-trust"))) %>% 
    mutate(across(to, factor, levels=c("low-trust","medium-trust","high-trust")))
                                    
  
    # Create a separate data frame with the background colors
  bg_colors <- data.frame(
    from = factor(c("low-trust", "medium-trust", "high-trust"), levels=c("low-trust","medium-trust","high-trust"))
  )
  
  # plotting code...
  ggplot() +
    geom_rect(data = bg_colors, aes(xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, fill = from), alpha = 0.1) +
    geom_line(data = df, aes(x = ret, y = probs, colour = as.factor(to))) +
    facet_wrap(~from, labeller = labeller(from = function(x) paste("From", x, "state on trial t"))) +
    ylim(c(0,1)) +
    scale_fill_manual(values = c("low-trust" = "red", "medium-trust" = "green", "high-trust" = "blue")) +
    labs(x = "Investor's net return on trial t", y = "Transition probability to \nState on trial t+1", color = 'State transitioned to') +
    theme_bw() +
    theme(legend.position = "bottom", 
          axis.title.y = element_text(size = 8, angle = 90, vjust = 1.5))
  
}

```

```{r}
ns <- 3
pars <- NULL

for (from in 1:ns){
  Tr_mat <- matrix(getpars(mod_3S)[seq(ns + 1 + (from - 1)*2*ns, ns + 1 + (from - 1)*2*ns + 2*ns - 1)],ncol=2)

colnames(Tr_mat) <- c("intercept","invPnL")
rownames(Tr_mat) <- c("to_1", "to_2", "to_3")
pars[[from]] <- Tr_mat
  
}

# pars has the format [[from]]["to","x"]
pars[[2]]


plot_HMM_transitions (3,pars)
  
```

```{r}
# pars has the format [[from]]["to","x"]
new_pars <- pars
new_pars[[1]]["to_1","invPnL"] <- 0
new_pars[[1]]["to_1","intercept"] <-  -10
new_pars[[1]]["to_3","intercept"] <-  -10

#new_pars[[2]]["to_1","intercept"] <- 5
plot_HMM_transitions (3,new_pars)
```



